Repository SzFMV2023-Osz/AutomatedCar-A, pull requests merged in 2023-10, with the labels that each got.

#31 Merge branch 'feature/ID-13-MovementVectorPacket' into develop-team-A1
  src/AutomatedCar/SystemComponents/Packets/MovementVectorPacket.cs
Labels: type: integration

#32 Merge branch 'develop-team-A1' into develop
  src/AutomatedCar/SystemComponents/Packets/IMovementVectorPacket.cs
  src/AutomatedCar/SystemComponents/Packets/InputHandling/IThrottle.cs
  src/AutomatedCar/SystemComponents/Packets/InputHandling/Throttle.cs
  src/AutomatedCar/SystemComponents/Packets/MovementVectorPacket.cs
Labels: type: integration

#49 Merge Develop_Team3_NPC into develop
  src/AutomatedCar/App.xaml.cs
  src/AutomatedCar/Assets/NPC_paths/NPC_oval_world_path.json
  src/AutomatedCar/Assets/NPC_paths/NPC_test_world_path.json
  src/AutomatedCar/AutomatedCar.csproj
  src/AutomatedCar/Models/NPC/Cordinates.cs
  src/AutomatedCar/Models/NPC/INPC.cs
  src/AutomatedCar/Models/NPC/NPCCar.cs
  src/AutomatedCar/Models/NPC/NPCManager.cs
  src/AutomatedCar/Models/NPC/NPCPathPoint.cs
  src/AutomatedCar/Models/NPC/Pedestrian.cs
  src/AutomatedCar/Models/World.cs
  src/AutomatedCar/ViewModels/PedestrianViewModel.cs
Labels: priority: normal

#40 Merge branch 'feature/ID-19-Wheel' to develop-team-A1
  src/AutomatedCar/SystemComponents/InputHandling/IWheel.cs
  src/AutomatedCar/SystemComponents/InputHandling/Wheel.cs
Labels: effort: low, type: integration
